import './globals.css';
import { Inter } from 'next/font/google';
import { Noto_Sans_KR, Roboto, Montserrat } from 'next/font/google';
import { Providers } from './Providers';

const inter = Inter({ subsets: ['latin'] });

export const notoSansKr = Noto_Sans_KR({
    preload: true, 
    subsets: ['latin'], 
    weight: ['100', '400', '700', '900'], 
});

export const roboto = Roboto({
    subsets: ['latin'], 
    weight: ['100', '400', '700'],
    variable: '--roboto', //
});
export const montserrat = Montserrat({
    subsets: ['latin'], 
    weight: ['100', '400', '700'],
});

export const metadata = {
    title: 'Study Dashboard',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body className={`{montserrat.className}`}>
                    <Providers>{children}</Providers>
            </body>
        </html>
    );
}
