import './globals.css';
import { Inter } from 'next/font/google';
import { Noto_Sans_KR, Roboto, Montserrat } from 'next/font/google';
import { Providers } from './Providers';

const inter = Inter({ subsets: ['latin'] });

export const notoSansKr = Noto_Sans_KR({
    // preload: true, 기본값
    subsets: ['latin'], // 또는 preload: false
    weight: ['100', '400', '700', '900'], // 가변 폰트가 아닌 경우, 사용할 fontWeight 배열
});

export const roboto = Roboto({
    subsets: ['latin'], // preload에 사용할 subsets입니다.
    weight: ['100', '400', '700'],
    variable: '--roboto', // CSS 변수 방식으로 스타일을 지정할 경우에 사용합니다.
});

export const metadata = {
    title: 'Study Dashboard',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='kr'>
            <body className={`{notoSansKr.className}`}>
                    <Providers>{children}</Providers>
            </body>
        </html>
    );
}
